### ISSUE TITLE
Can u guys add download option too in different qualities pls nd also can u put a section for downloaded videos too?

### ISSUE THREAD

**Issue by Aruraka** [raffyamoguis/watchlistify-re#23]

**Comment by raffyxyz** [comment]
It's possible to add download feature, but I'm not sure what you mean by a section for downloaded videos.

**Comment by Aruraka** [comment]
> It's possible to add download feature, but I'm not sure what you mean by a section for downloaded videos.

By a section for downloaded videos I meant a section where the downloaded videos will be stored in the app

**Comment by raffyxyz** [comment]
> > It's possible to add download feature, but I'm not sure what you mean by a section for downloaded videos.
> 
> By a section for downloaded videos I meant a section where the downloaded videos will be stored in the app

In order to achieve that I need to access the users download directory I'm not really sure if it's possible to do that on a web app. It would be best if the app is native windows app or android app but it's a web application.

**Comment by Aruraka** [comment]
> > > It's possible to add download feature, but I'm not sure what you mean by a section for downloaded videos.
> > 
> > 
> > By a section for downloaded videos I meant a section where the downloaded videos will be stored in the app
> 
> In order to achieve that I need to access the users download directory I'm not really sure if it's possible to do that on a web app. It would be best if the app is native windows app or android app but it's a web application.

That's ok is it possible to put a download option only? Nd do u have discord or telegram where u can notify me after u put the download button there?

**Comment by raffyxyz** [comment]
> > > > It's possible to add download feature, but I'm not sure what you mean by a section for downloaded videos.
> > > 
> > > 
> > > By a section for downloaded videos I meant a section where the downloaded videos will be stored in the app
> > 
> > In order to achieve that I need to access the users download directory I'm not really sure if it's possible to do that on a web app. It would be best if the app is native windows app or android app but it's a web application.
> 
> That's ok is it possible to put a download option only? Nd do u have discord or telegram where u can notify me after u put the download button there?

My discord user ryzonxyz
